runtime: go116
main: ./tour

env_variables:
  TOUR_ANALYTICS: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-11222381-5"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "UA-11222381-5");
    gtag("config", "UA-49880327-6");
    </script>

handlers:
- url: /.*
  script: auto
  secure: always
